"""Reproduce the descriptive statistics in paper.tex from checked-in JSON runs."""

import glob
import json
import math
import statistics as stats
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ENGINES = ("MySQL", "PostgreSQL", "RocksDB", "LevelDB", "Cassandra")
T_975_DF2 = 4.3026527299


def mean_ci(values):
    return stats.mean(values), T_975_DF2 * stats.stdev(values) / math.sqrt(len(values))


def phase_mean(run, start, stop, field):
    points = run["time_series"][start:stop]
    if field == "throughput":
        return stats.mean(p["throughput_ops"] for p in points)
    return stats.mean(p["latency_stats"]["p99_us"] for p in points)


def main():
    lines = [
        "% Generated by python3 scripts/paper_analysis.py; do not edit by hand.",
        "\\begin{table}[htbp]",
        "\\centering\\small",
        "\\caption{Thirty-second Workload Shifter pilot runs (three runs per configuration). Values are recorded completed adapter-call rates and call latencies; operation success was not recorded. Means and descriptive two-sided 95\\% Student-$t$ intervals use runs as the unit. Recovery is the within-run Phase 3/Phase 1 call-rate ratio. P99 is the whole-run value.}",
        "\\label{tab:observed}",
        "\\begin{tabular}{@{}lrrr@{}}\\toprule",
        "Configuration & Call rate (calls/s) & Whole-run P99 ($\\mu$s) & Return/baseline \\\\ \\midrule",
    ]
    plot_commands = []
    boundary_commands = []
    phase_rows = []
    normalized_series = {}
    plot_styles = {"RocksDB": (1, "mark=*,color=lsmgreen"),
                   "MySQL": (2, "mark=square*,color=btreeblue"),
                   "PostgreSQL": (3, "mark=triangle*,color=cliffgray"),
                   "LevelDB": (4, "mark=diamond*,color=green!45!black"),
                   "Cassandra": (5, "mark=pentagon*,color=orange!75!black")}
    for engine in ENGINES:
        files = sorted(glob.glob(str(ROOT / "results" / f"results_{engine.lower()}_run*.json")))
        if len(files) != 3:
            raise ValueError(f"Expected three runs for {engine}, found {len(files)}")
        runs = [json.loads(Path(f).read_text()) for f in files]
        if any(len(run["time_series"]) != 30 for run in runs):
            raise ValueError(f"Expected 30 time-series points for {engine}")
        throughput = [run["throughput_ops"] for run in runs]
        p99 = [run["latency_stats"]["p99_us"] for run in runs]
        recovery = [phase_mean(run, 20, 30, "throughput") / phase_mean(run, 0, 10, "throughput") for run in runs]
        interior_recovery = [
            phase_mean(run, 21, 29, "throughput") /
            phase_mean(run, 1, 9, "throughput") for run in runs
        ]
        boundary_commands.append(
            f"\\newcommand{{\\{engine}InteriorRecovery}}{{{stats.mean(interior_recovery):.2f}}}"
        )
        normalized_series[engine.lower()] = [
            stats.mean(run["time_series"][i]["throughput_ops"] /
                       phase_mean(run, 0, 10, "throughput") for run in runs)
            for i in range(30)
        ]
        tm, tc = mean_ci(throughput)
        pm, pc = mean_ci(p99)
        rm, rc = mean_ci(recovery)
        lines.append(f"{engine} & ${tm:,.0f}\\pm{tc:,.0f}$ & ${pm:.1f}\\pm{pc:.1f}$ & ${rm:.2f}\\pm{rc:.2f}$ \\\\")
        if engine in plot_styles:
            x_center, style = plot_styles[engine]
            coords = " ".join(f"({x_center + (i - 1) * .1:.1f},{ratio:.3f})"
                              for i, ratio in enumerate(recovery))
            plot_commands.append(
                f"\\newcommand{{\\{engine}RecoveryPlot}}{{\\addplot[only marks,{style},mark size=2.4pt] coordinates {{{coords}}};}}"
            )
        phase_cells = []
        for start, stop in ((0, 10), (10, 20), (20, 30)):
            values = [phase_mean(run, start, stop, "throughput") for run in runs]
            phase_cells.append(f"${stats.mean(values):,.0f}\\pm{stats.stdev(values):,.0f}$")
        phase_rows.append(engine + " & " + " & ".join(phase_cells) + r" \\")
    lines += ["\\bottomrule\\end{tabular}", "\\end{table}"]
    lines += [
        "\\begin{table}[htbp]",
        "\\centering\\small",
        "\\caption{Mean recorded adapter-call rate in each nominal phase, averaged within runs and then across three runs (mean $\\pm$ between-run standard deviation, calls/s). Time points within a run are not independent replicates.}",
        "\\label{tab:phases}",
        "\\begin{tabular}{@{}lrrr@{}}\\toprule",
        "Configuration & Baseline & Stress & Return \\\\ \\midrule",
        *phase_rows,
        "\\bottomrule\\end{tabular}",
        "\\end{table}",
    ]
    (ROOT / "paper_data.tex").write_text(
        "\n".join(plot_commands + boundary_commands + lines) + "\n"
    )
    series_lines = ["second mysql postgresql rocksdb leveldb cassandra"]
    for i in range(30):
        values = " ".join(f"{normalized_series[engine.lower()][i]:.6f}"
                          for engine in ENGINES)
        series_lines.append(f"{i + 1} {values}")
    (ROOT / "paper_timeseries.dat").write_text("\n".join(series_lines) + "\n")


if __name__ == "__main__":
    main()
